import { CRList } from '@sovereignbase/convergent-replicated-list'
import type { Person } from 'schema-dts'
import { award, additionalName } from '../../.shared/index.js'

type SchemaOrgPersonRaw = Extract<Person, { '@type': 'Person' }>
export type SchemaOrgPerson = Partial<
  Record<keyof SchemaOrgPersonRaw, SchemaOrgPersonRaw[keyof SchemaOrgPersonRaw]>
>

export const defaults = {
  award,
  additionalName,
  address: new CRList<string>().toJSON(),
  affiliation: '',
  agentInteractionStatistic: '',
  alumniOf: '',
  birthDate: '',
  birthPlace: '',
  brand: '',
  callSign: new CRList<string>().toJSON(),
  children: '',
  colleague: new CRList<string>().toJSON(),
  contactPoint: '',
  deathDate: '',
  deathPlace: '',
  duns: new CRList<string>().toJSON(),
  email: new CRList<string>().toJSON(),
  familyName: new CRList<string>().toJSON(),
  faxNumber: new CRList<string>().toJSON(),
  follows: '',
  funder: '',
  funding: '',
  gender: new CRList<string>().toJSON(),
  givenName: new CRList<string>().toJSON(),
  globalLocationNumber: new CRList<string>().toJSON(),
  hasCertification: '',
  hasCredential: '',
  hasOccupation: '',
  hasOfferCatalog: '',
  hasPOS: '',
  height: '',
  homeLocation: '',
  honorificPrefix: new CRList<string>().toJSON(),
  honorificSuffix: new CRList<string>().toJSON(),
  interactionStatistic: '',
  isicV4: new CRList<string>().toJSON(),
  jobTitle: new CRList<string>().toJSON(),
  knows: '',
  knowsAbout: new CRList<string>().toJSON(),
  knowsLanguage: new CRList<string>().toJSON(),
  lifeEvent: '',
  makesOffer: '',
  memberOf: '',
  naics: new CRList<string>().toJSON(),
  nationality: '',
  netWorth: '',
  owns: '',
  parent: '',
  performerIn: '',
  pronouns: new CRList<string>().toJSON(),
  publishingPrinciples: new CRList<string>().toJSON(),
  relatedTo: '',
  seeks: '',
  sibling: '',
  skills: new CRList<string>().toJSON(),
  sponsor: '',
  spouse: '',
  taxID: new CRList<string>().toJSON(),
  telephone: new CRList<string>().toJSON(),
  vatID: new CRList<string>().toJSON(),
  weight: '',
  workLocation: '',
  worksFor: '',
  additionalType: new CRList<string>().toJSON(),
  alternateName: new CRList<string>().toJSON(),
  description: new CRList<string>().toJSON(),
  disambiguatingDescription: new CRList<string>().toJSON(),
  identifier: new CRList<string>().toJSON(),
  image: new CRList<string>().toJSON(),
  mainEntityOfPage: new CRList<string>().toJSON(),
  name: new CRList<string>().toJSON(),
  owner: '',
  potentialAction: '',
  sameAs: new CRList<string>().toJSON(),
  subjectOf: '',
  url: new CRList<string>().toJSON(),
} as const

type MissingKeys = Exclude<keyof SchemaOrgPerson, keyof typeof defaults>
type ExtraKeys = Exclude<keyof typeof defaults, keyof SchemaOrgPerson>
