import type { SchemaOrgPerson } from '../.types/index.js'
import { CRStruct } from '@sovereignbase/convergent-replicated-struct'

export class Person {
  public readonly state: SchemaOrgPerson
  constructor() {
    this.state = new CRStruct<SchemaOrgPerson>({
      '@type': 'Person',
      additionalName: '',
      address: '',
      affiliation: '',
      agentInteractionStatistic: '',
      alumniOf: '',
      award: '',
      birthDate: '',
      birthPlace: '',
      brand: '',
      callSign: '',
      children: '',
      colleague: '',
      contactPoint: '',
      deathDate: '',
      deathPlace: '',
      duns: '',
      email: '',
      familyName: '',
      faxNumber: '',
      follows: '',
      funder: '',
      funding: '',
      gender: '',
      givenName: '',
      globalLocationNumber: '',
      hasCertification: '',
      hasCredential: '',
      hasOccupation: '',
      hasOfferCatalog: '',
      hasPOS: '',
      height: '',
      homeLocation: '',
      honorificPrefix: '',
      honorificSuffix: '',
      interactionStatistic: '',
      isicV4: '',
      jobTitle: '',
      knows: '',
      knowsAbout: '',
      knowsLanguage: '',
      lifeEvent: '',
      makesOffer: '',
      memberOf: '',
      naics: '',
      nationality: '',
      netWorth: '',
      owns: '',
      parent: '',
      performerIn: '',
      pronouns: '',
      publishingPrinciples: '',
      relatedTo: '',
      seeks: '',
      sibling: '',
      skills: '',
      sponsor: '',
      spouse: '',
      taxID: '',
      telephone: '',
      vatID: '',
      weight: '',
      workLocation: '',
      worksFor: '',
      additionalType: '',
      alternateName: '',
      description: '',
      disambiguatingDescription: '',
      identifier: '',
      image: '',
      mainEntityOfPage: '',
      name: '',
      owner: '',
      potentialAction: '',
      sameAs: '',
      subjectOf: '',
      url: '',
    })
  }
}

const user = new Person().state.identifier
