import type { Organization } from 'schema-dts'

type SchemaOrgOrganizationRaw = Extract<
  Organization,
  { '@type': 'Organization' }
>

export type SchemaOrgOrganization = Partial<
  Record<
    keyof SchemaOrgOrganizationRaw,
    SchemaOrgOrganizationRaw[keyof SchemaOrgOrganizationRaw]
  >
>

export const defaults = {
  acceptedPaymentMethod: '',
  actionableFeedbackPolicy: '',
  address: '',
  agentInteractionStatistic: '',
  aggregateRating: '',
  alumni: '',
  areaServed: '',
  award: '',
  brand: '',
  companyRegistration: '',
  contactPoint: '',
  correctionsPolicy: '',
  department: '',
  dissolutionDate: '',
  diversityPolicy: '',
  diversityStaffingReport: '',
  duns: '',
  email: '',
  employee: '',
  ethicsPolicy: '',
  event: '',
  faxNumber: '',
  founder: '',
  foundingDate: '',
  foundingLocation: '',
  funder: '',
  funding: '',
  globalLocationNumber: '',
  hasCertification: '',
  hasCredential: '',
  hasGS1DigitalLink: '',
  hasMemberProgram: '',
  hasMerchantReturnPolicy: '',
  hasOfferCatalog: '',
  hasPOS: '',
  hasShippingService: '',
  interactionStatistic: '',
  isicV4: '',
  iso6523Code: '',
  keywords: '',
  knowsAbout: '',
  knowsLanguage: '',
  legalAddress: '',
  legalName: '',
  legalRepresentative: '',
  leiCode: '',
  location: '',
  logo: '',
  makesOffer: '',
  member: '',
  memberOf: '',
  naics: '',
  nonprofitStatus: '',
  numberOfEmployees: '',
  ownershipFundingInfo: '',
  owns: '',
  parentOrganization: '',
  publishingPrinciples: '',
  review: '',
  seeks: '',
  skills: '',
  slogan: '',
  sponsor: '',
  subOrganization: '',
  taxID: '',
  telephone: '',
  unnamedSourcesPolicy: '',
  vatID: '',

  additionalType: '',
  alternateName: '',
  description: '',
  disambiguatingDescription: '',
  identifier: '',
  image: '',
  mainEntityOfPage: '',
  name: '',
  owner: '',
  potentialAction: '',
  sameAs: '',
  subjectOf: '',
  url: '',
} as const

type MissingKeys = Exclude<keyof SchemaOrgOrganization, keyof typeof defaults>
type ExtraKeys = Exclude<keyof typeof defaults, keyof SchemaOrgOrganization>
