import type { ImageObject } from 'schema-dts'
import {
  additionalType,
  alternateName,
  caption,
  description,
  disambiguatingDescription,
  embeddedTextCaption,
} from '../../.shared/index.js'

type SchemaOrgImageObjectRaw = Extract<ImageObject, { '@type': 'ImageObject' }>

export type SchemaOrgImageObject = Partial<SchemaOrgImageObjectRaw>

export const defaults = {
  '@id': '' as string,
  '@type': 'ImageObject',
  caption,
  embeddedTextCaption,
  exifData: '',
  representativeOfPage: false as boolean,
  associatedArticle: '',
  bitrate: '',
  contentSize: '',
  contentUrl: '',
  duration: '',
  embedUrl: '',
  encodesCreativeWork: '',
  encodingFormat: '',
  endTime: '',
  height: '',
  ineligibleRegion: '',
  interpretedAsClaim: '',
  playerType: '',
  productionCompany: '',
  regionsAllowed: '',
  requiresSubscription: false as boolean,
  sha256: '',
  startTime: '',
  uploadDate: '',
  width: '',
  about: '',
  abstract: '',
  accessMode: '',
  accessModeSufficient: '',
  accessibilityAPI: '',
  accessibilityControl: '',
  accessibilityFeature: '',
  accessibilityHazard: '',
  accessibilitySummary: '',
  accountablePerson: '',
  acquireLicensePage: '',
  aggregateRating: '',
  alternativeHeadline: '',
  archivedAt: '',
  assesses: '',
  associatedMedia: '',
  audience: '',
  audio: '',
  author: '',
  award: '',
  character: '',
  citation: '',
  comment: '',
  commentCount: 0 as number,
  conditionsOfAccess: '',
  contentLocation: '',
  contentRating: '',
  contentReferenceTime: '',
  contributor: '',
  copyrightHolder: '',
  copyrightNotice: '',
  copyrightYear: 0 as number,
  correction: '',
  countryOfOrigin: '',
  creativeWorkStatus: '',
  creator: '',
  creditText: '',
  dateCreated: '',
  dateModified: '',
  datePublished: '',
  digitalSourceType: '',
  discussionUrl: '',
  displayLocation: '',
  editEIDR: '',
  editor: '',
  educationalAlignment: '',
  educationalLevel: '',
  educationalUse: '',
  encoding: '',
  exampleOfWork: '',
  expires: '',
  funder: '',
  funding: '',
  genre: '',
  hasPart: '',
  headline: '',
  inLanguage: '',
  interactionStatistic: '',
  interactivityType: '',
  isAccessibleForFree: false,
  isBasedOn: '',
  isFamilyFriendly: false,
  isPartOf: '',
  keywords: '',
  learningResourceType: '',
  license: '',
  locationCreated: '',
  mainEntity: '',
  maintainer: '',
  material: '',
  materialExtent: '',
  mentions: '',
  offers: '',
  pattern: '',
  position: '',
  producer: '',
  provider: '',
  publication: '',
  publisher: '',
  publisherImprint: '',
  publishingPrinciples: '',
  recordedAt: '',
  releasedEvent: '',
  review: '',
  schemaVersion: '',
  sdDatePublished: '',
  sdLicense: '',
  sdPublisher: '',
  size: '',
  sourceOrganization: '',
  spatial: '',
  spatialCoverage: '',
  sponsor: '',
  teaches: '',
  temporal: '',
  temporalCoverage: '',
  text: '',
  thumbnail: '',
  thumbnailUrl: '',
  timeRequired: '',
  translationOfWork: '',
  translator: '',
  typicalAgeRange: '',
  usageInfo: '',
  version: '',
  video: '',
  wordCount: 0,
  workExample: '',
  workTranslation: '',
  additionalType,
  alternateName,
  description,
  disambiguatingDescription,
  identifier: '' as string,
  image: '',
  mainEntityOfPage: '',
  name: '',
  owner: '',
  potentialAction: '',
  sameAs: '',
  subjectOf: '',
  url: '',
} as const

// "awards" | "encodings" | "fileFormat" | "isBasedOnUrl" | "reviews" are legacy
type MissingKeys = Exclude<keyof SchemaOrgImageObject, keyof typeof defaults>

type ExtraKeys = Exclude<keyof typeof defaults, keyof SchemaOrgImageObject>

export type CRImageObject = Partial<typeof defaults>
